version: '2.0'
services:
#  web:
#    build: .
#    ports:
#    - "8000:8080"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

